import { readFileSync, writeFileSync } from "node:fs";
import { mkdtemp } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { parse } from "yaml";
import { describe, expect, it } from "vitest";
import { buildConfig, ensureGitignore, readConfig, writeConfig } from "../src/init/config.js";
import { runInit } from "../src/init/index.js";
import { ConfigSchema } from "../src/types.js";

async function tempProject(): Promise<string> {
  return mkdtemp(path.join(os.tmpdir(), "design-gate-config-"));
}

function detected() {
  return {
    framework: { framework: "next" as const, router: "app" as const },
    devServer: {
      script: "next dev",
      scriptName: "dev" as const,
      command: "pnpm run dev",
      port: 3000,
      url: "http://localhost:3000",
    },
    routes: ["/", "/pricing"],
  };
}

describe("init configuration", () => {
  it("writes YAML that parses through ConfigSchema", async () => {
    const cwd = await tempProject();
    const config = buildConfig(detected());
    writeConfig(cwd, config);
    const raw = readFileSync(path.join(cwd, "design-gate.yml"), "utf8");
    expect(raw).toMatch(/^# Generated by design-gate init/);
    expect(() => ConfigSchema.parse(parse(raw))).not.toThrow();
    expect(readConfig(cwd)).toEqual(config);
  });

  it("deep-merges defaults while preserving existing user values", async () => {
    const cwd = await tempProject();
    writeFileSync(path.join(cwd, "design-gate.yml"), `
version: 1
enabled: false
devServer:
  url: http://localhost:9999
routes:
  - /custom
observer: none
`, "utf8");
    const merged = writeConfig(cwd, buildConfig(detected()), { merge: true });
    expect(merged.enabled).toBe(false);
    expect(merged.devServer.url).toBe("http://localhost:9999");
    expect(merged.devServer.command).toBe("pnpm run dev");
    expect(merged.routes).toEqual(["/custom"]);
    expect(merged.observer).toBe("none");
  });

  it("adds the run directory to gitignore exactly once", async () => {
    const cwd = await tempProject();
    writeFileSync(path.join(cwd, ".gitignore"), "node_modules\n", "utf8");
    ensureGitignore(cwd);
    ensureGitignore(cwd);
    expect(readFileSync(path.join(cwd, ".gitignore"), "utf8")).toBe("node_modules\n.design-gate/\n");
  });

  it("runs zero-config initialization non-interactively without network access", async () => {
    const cwd = await tempProject();
    const home = await tempProject();
    writeFileSync(path.join(cwd, "index.html"), "<!doctype html><title>Static</title>", "utf8");
    const messages: string[] = [];
    const result = await runInit({ cwd, home, env: {}, interactive: false, log: (message) => messages.push(message) });
    expect(result.config.devServer.url).toBe("http://localhost:4173");
    expect(result.brand.name).toBe(path.basename(cwd));
    expect(result.skillInstall.installed).toHaveLength(2);
    expect(result.key.source).toBe("none");
    expect(messages).toContain("No TypeSafe API key found; facts-only mode will run until `design-gate login`.");
    expect(readConfig(cwd)).not.toBeNull();
  });
});
