import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { parse, stringify } from "yaml";
import { BrandSchema, ConfigSchema, type Brand, type Config } from "../types.js";
import { defaultUiGlobs, type DevServerDetection, type Framework, type FrameworkDetection } from "./detect.js";

export interface DetectedProject {
  framework: Framework | FrameworkDetection;
  devServer: DevServerDetection;
  routes: string[];
  uiGlobs?: string[];
}

export interface MergeOptions {
  merge?: boolean;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return Boolean(value) && typeof value === "object" && !Array.isArray(value);
}

function existingWins(existing: unknown, additions: unknown): unknown {
  if (!isRecord(existing) || !isRecord(additions)) return existing === undefined ? additions : existing;
  const merged: Record<string, unknown> = { ...additions };
  for (const [key, value] of Object.entries(existing)) {
    merged[key] = key in additions ? existingWins(value, additions[key]) : value;
  }
  return merged;
}

export function buildConfig(detected: DetectedProject): Config {
  return ConfigSchema.parse({
    version: 1,
    enabled: true,
    devServer: {
      url: detected.devServer.url,
      ...(detected.devServer.command ? { command: detected.devServer.command } : {}),
      autoStart: Boolean(detected.devServer.command),
      readyTimeoutMs: 60_000,
    },
    routes: detected.routes,
    uiGlobs: detected.uiGlobs ?? defaultUiGlobs(detected.framework),
    brandFile: "brand.json",
    observer: "agent",
    observerModel: "claude-opus-5",
    judge: "jev",
    jevModel: "jev-latest",
    thresholds: {},
    categoryWeights: {},
  });
}

export function readConfig(cwd: string): Config | null {
  const file = path.join(cwd, "design-gate.yml");
  if (!existsSync(file)) return null;
  return ConfigSchema.parse(parse(readFileSync(file, "utf8")));
}

export function writeConfig(cwd: string, config: Config, options: MergeOptions = { merge: true }): Config {
  const file = path.join(cwd, "design-gate.yml");
  let output: unknown = config;
  if (options.merge !== false && existsSync(file)) {
    const existing = parse(readFileSync(file, "utf8")) as unknown;
    output = existingWins(existing, config);
  }
  const validated = ConfigSchema.parse(output);
  writeFileSync(file, `# Generated by design-gate init. Existing values are preserved on re-run.\n${stringify(validated)}`, "utf8");
  return validated;
}

export function ensureGitignore(cwd: string): void {
  const file = path.join(cwd, ".gitignore");
  const current = existsSync(file) ? readFileSync(file, "utf8") : "";
  if (current.split(/\r?\n/).some((line) => line.trim() === ".design-gate/")) return;
  const prefix = current.length === 0 || current.endsWith("\n") ? current : `${current}\n`;
  writeFileSync(file, `${prefix}.design-gate/\n`, "utf8");
}

export function writeBrand(cwd: string, brand: Brand, options: MergeOptions = { merge: true }): Brand {
  const file = path.join(cwd, "brand.json");
  let output: unknown = brand;
  if (options.merge !== false && existsSync(file)) {
    const existing = JSON.parse(readFileSync(file, "utf8")) as unknown;
    output = existingWins(existing, brand);
  }
  const validated = BrandSchema.parse(output);
  writeFileSync(file, `${JSON.stringify(validated, null, 2)}\n`, "utf8");
  return validated;
}
